<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13051" started-at="2015-11-04T10:38:27Z" finished-at="2015-11-04T10:38:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13051" started-at="2015-11-04T10:38:27Z" finished-at="2015-11-04T10:38:40Z">
      <class name="Social_Collaboration.Document">
        <test-method status="FAIL" signature="login()[pri:0, instance:Social_Collaboration.Document@1ea7d34]" name="login" is-config="true" duration-ms="0" started-at="2015-11-04T16:08:27Z" finished-at="2015-11-04T16:08:27Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Social_Collaboration.Document.login(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="SKIP" signature="addFolder()[pri:0, instance:Social_Collaboration.Document@1ea7d34]" name="addFolder" duration-ms="0" started-at="2015-11-04T16:08:40Z" finished-at="2015-11-04T16:08:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addFolder -->
        <test-method status="SKIP" signature="addDoc()[pri:0, instance:Social_Collaboration.Document@1ea7d34]" name="addDoc" duration-ms="1" started-at="2015-11-04T16:08:40Z" finished-at="2015-11-04T16:08:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addDoc -->
        <test-method status="SKIP" signature="checkDoc()[pri:0, instance:Social_Collaboration.Document@1ea7d34]" name="checkDoc" duration-ms="1" started-at="2015-11-04T16:08:40Z" finished-at="2015-11-04T16:08:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkDoc -->
      </class> <!-- Social_Collaboration.Document -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
